"""empty message

Revision ID: 233e3a09d289
Revises: 62b571bfdade
Create Date: 2024-05-14 21:40:04.822062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233e3a09d289'
down_revision: Union[str, None] = '62b571bfdade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mapping', sa.Column('shorten_key', sa.String(), nullable=True))
    op.drop_constraint('url_mapping_short_key_key', 'url_mapping', type_='unique')
    op.create_unique_constraint(None, 'url_mapping', ['shorten_key'])
    op.drop_column('url_mapping', 'short_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mapping', sa.Column('short_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'url_mapping', type_='unique')
    op.create_unique_constraint('url_mapping_short_key_key', 'url_mapping', ['short_key'])
    op.drop_column('url_mapping', 'shorten_key')
    # ### end Alembic commands ###
