"""empty message

Revision ID: aac8394825de
Revises: 233e3a09d289
Create Date: 2024-05-16 10:45:55.411635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac8394825de'
down_revision: Union[str, None] = '233e3a09d289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('url_mapping_origin_url_key', 'url_mapping', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('url_mapping_origin_url_key', 'url_mapping', ['origin_url'])
    # ### end Alembic commands ###
